### ISSUE TITLE
1.81 doesn't seem to work properly.

### ISSUE THREAD

**Issue by pet443** [KingKrouch/dbzk_fps#2]
If the game is run with the x64 exe in the folder itself it seems to work. But the DLC is not recognized this way.

If run through steam itself it won't trigger and run at 60fps.

**Comment by KingKrouch** [comment]
Give the new release a try. It should work with the 2.02 patch of the game.

**Comment by KingKrouch** [comment]
I have updated the mod to support the latest version of the game. However, the repository is a blank slate, and I'm archiving this repository. A download is in the Releases section:

https://github.com/KingKrouch/DBZK_Fix
