### ISSUE TITLE
The mod causes frame spikes/drops/hitches, resulting in visible stutter breaking smooth frame pacing/cadence.

### ISSUE THREAD

**Issue by BParks21** [KingKrouch/dbzk_fps#3]
With this mod installed the game has little micro stutters even at lowest possible settings removing the mod eliminates these hitches. I'm running the latest Windows 11 build  with a 12700k, 3080, and 64gb of ram @120hz with gsync. Something with this mod causes weird performance hitches. I have in game vsync off with it forced in the control panel. No combination of vysnc on or off resolves the issue. You can easily observe this by standing still and slowly rotating the camera. This was prior to game version 1.91 and still occurs in that version as well.

**Comment by yewhan** [comment]
I'm currently playing with the latest asi loader version ([https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/latest](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/latest)) and am having no micro-stutters whatsoever.
Tho that being said, I didn't have any micro-stutters when I first installed using the super outdated asi loader.
Win 10 19045, r5 3600, radeon 5700xt, 32gb ram @3600 MHz CL16, with a freesync 170 Hz monitor.

**Comment by BParks21** [comment]
Can you provide a video that includes a fps and frametime graph/counter while slowly panning the camera around for a good 3-5 min?

**Comment by yewhan** [comment]
yeah sure, I'll try get a video in a sec

**Comment by yewhan** [comment]
> Can you provide a video that includes a fps and frametime graph/counter while slowly panning the camera around for a good 3-5 min?

so I couldn't show the frame time on the screen using the AMD overlay (and cba to download something to show that rn), so instead I just logged the FPS every .25 seconds, calculated the frame times myself, as well as the min, max and mean frame times. **You can find the log yourself here: [https://gist.github.com/yewhan/a53393cbc193f2b85b8634df8b0f9024](https://gist.github.com/yewhan/a53393cbc193f2b85b8634df8b0f9024)**
This was done with me slowly turning my camera for 3 mins, @ 1440p on max settings with some mods on (can be seen [here](https://i.imgur.com/jZHzvKa.png)).

**Comment by yewhan** [comment]
I've just downloaded afterburner, so when I get to an open-world spot that isn't barren I'll try get a video.

**Comment by Rings4** [comment]
> I've just downloaded afterburner, so when I get to an open-world spot that isn't barren I'll try get a video.

So, any ETA on that video?

**Comment by KingKrouch** [comment]
I have updated the mod to support the latest version of the game. However, the repository is a blank slate, and I'm archiving this repository. A download is in the Releases section. This should work better with the game, as it's not constantly writing variables to memory in a loop, instead it relies on hooking:

https://github.com/KingKrouch/DBZK_Fix
