### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Lethlman** [KingKrouch/dbzk_fps#4]
It doesn't work at all. I put it in the WIN64 directory and when I launched the game it say it cant load the ASI. Then I put it in the plugins folder and still nothing.
![image](https://github.com/KingKrouch/dbzk_fps/assets/101858300/790db74b-c9c5-4e5b-93c9-e5cd3752b1bd)

**Comment by KingKrouch** [comment]
Try the CLion-Test version's DLL file.

**Comment by Lethlman** [comment]
> Try the CLion-Test version's DLL file.

That did it, thank you

**Comment by KingKrouch** [comment]
I have updated the mod to support the latest version of the game. However, the repository is a blank slate, and I'm archiving this repository. A download is in the Releases section:

https://github.com/KingKrouch/DBZK_Fix
