### ISSUE TITLE
Latest update broke the mod

### ISSUE THREAD

**Issue by Brandonspikes** [KingKrouch/dbzk_fps#5]

**Comment by TheBladedBeast** [comment]
Yeah, neither of the versions work for me either.

**Comment by Almahdi672** [comment]
Yeah, it sucks cause the game has terrible performance when you enter surge mode in 60FPS. It's borderline unplayable. Playing it at 165FPS fixed the issue but now the mod stopped working sadly. I really hope KingKrouch will update this mod cause it was a lifesaver.

**Comment by AmroDK** [comment]
Yes this needs an update, I cant play dlc 6 with caped frames, its horrible and very noticable, please update 😭

**Comment by STBlitzkrieg** [comment]
I'd appreciate an update to this as well - I'll be patiently waiting to play this again until this tool is update.

Thanks for all of your work. I think I speak for all of us when I say that you've made this game playable for some of us FPS snobs. 😄

**Comment by rooxon** [comment]
adding to that, with the news of that new budokai game coming, this was likely the last or at the most, before-last update barring hotfixes... we likely need only one final version of this and thank you a ton in advance <3

**Comment by TheBladedBeast** [comment]
He’s working on it right now in a different way that can’t be patched out

**Comment by KingKrouch** [comment]
I have updated the mod to support the latest version of the game. However, the repository is a blank slate, and I'm archiving this repository. A download is in the Releases section:

https://github.com/KingKrouch/DBZK_Fix
