### ISSUE TITLE
Please update this mod for 2.10

### ISSUE THREAD

**Issue by nabilliondolla** [KingKrouch/dbzk_fps#7]
This mod isn't working for me on the newest update.

**Comment by LostandStranded** [comment]
I second this. Please get it rolling for 2.10

There is so little support for this game from the actual devs. It's modders and developers like you who keep these things playable for the little people.

**Comment by TheNovaBeast** [comment]
As someone who has a 170hz DP monitor this game is unplayable at 60fps

If you can make a Vortex version which installs via vortex mod manager and it adds a toggle in game settings or even on start up your desired fps, for 2.10

I'll donate $70 and I'm not joking

**Comment by KingKrouch** [comment]
> As someone who has a 170hz DP monitor this game is unplayable at 60fps
> 
> If you can make a Vortex version which installs via vortex mod manager and it adds a toggle in game settings or even on start up asks your desired fps before booting up, for 2.10
> 
> I'll donate $70 and I'm not joking (as long as it's PayPal)

PayPal is fine. Right now, I'm working on finding some function hooks in UE4SS, so I can have the mod available that way (where I won't have to constantly change memory offsets each update).

Just that since the game itself constantly changes the framerate cap after cutscenes and when saving/loading settings, it's causing some issues with keeping the framerate cap in place.

I have an ultrawide patch in UE4SS partially working likewise, but I need to figure out how to modify a few things to make it a good fix.

**Comment by TheNovaBeast** [comment]
> > As someone who has a 170hz DP monitor this game is unplayable at 60fps
> > 
> > If you can make a Vortex version which installs via vortex mod manager and it adds a toggle in game settings or even on start up asks your desired fps before booting up, for 2.10
> > 
> > I'll donate $70 and I'm not joking (as long as it's PayPal)
> 
> PayPal is fine. Right now, I'm working on finding some function hooks in UE4SS, so I can have the mod available that way (where I won't have to constantly change memory offsets each update).
> 
> Just that since the game itself constantly changes the framerate cap after cutscenes and when saving/loading settings, it's causing some issues with keeping the framerate cap in place.
> 
> I have an ultrawide patch in UE4SS partially working likewise, but I need to figure out how to modify a few things to make it a good fix.

I can donate that on the 27th, I am really looking forward to what you can do with this, and yeah the fps changing for the game with cutscenes sound like pain. If you ever do get a 2.10 FPS mod that I can run with the mod launcher such as vortex though I will be very happy but I will definitely like to try what you have got

My discord is FireFlyFlying

If you add me I'll edit it out I'd love to test what you have and stuff to help you debug things even though I have 0 code knowledge c:

**Comment by KingKrouch** [comment]
I have updated the mod to support the latest version of the game. However, the repository is a blank slate, and I'm archiving this repository. A download is in the Releases section:

https://github.com/KingKrouch/DBZK_Fix
